theme: jekyll-theme-minimal

title: Curatorial Voice
description: A [Sussex Humanities Lab](http://www.sussex.ac.uk/shl/) project
logo: /assets/images/BA-UoS-SHL-combinedlogo2.png
show_downloads: true
