theme: jekyll-theme-minimal

title: Curatorial Voice
subtitle: Legacy Descriptions of Art Objects and their Contemporary Uses
description: Legacy Descriptions of Art Objects and their Contemporary Uses
logo: /assets/images/BA-UoS-SHL-combinedlogo2.png
show_downloads: true
